services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: stocksavvy-db
    environment:
      POSTGRES_DB: smart_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stocksavvy_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: stocksavvy-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: